apiVersion: v1
kind: Service
metadata:
  name: ms-admon-service
spec:
  selector:
    app: ms-admon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-admon-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-admon
  template:
    metadata:
      labels:
        app: ms-admon
    spec:
      containers:
        - name: ms-admon-container
          image: nicolasdcubillos/img-ms-admon:v1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
