apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pedidos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pedidos
  template:
    metadata:
      labels:
        app: ms-pedidos
    spec:
      containers:
      - name: ms-pedidos-container
        image: nicolasdcubillos/img-ms-pedidos:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: ms-pedidos-service
spec:
  selector:
    app: ms-pedidos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: NodePort