apiVersion: v1
kind: Service
metadata:
  name: ms-reservas-service
spec:
  selector:
    app: ms-reservas
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-reservas-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-reservas
  template:
    metadata:
      labels:
        app: ms-reservas
    spec:
      containers:
        - name: ms-reservas-container
          image: nicolasdcubillos/img-ms-reservas:v1.0
          ports:
            - containerPort: 8084
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
