apiVersion: v1
kind: Service
metadata:
  name: ms-pagos-service
spec:
  selector:
    app: ms-pagos
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pagos-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-pagos
  template:
    metadata:
      labels:
        app: ms-pagos
    spec:
      containers:
        - name: ms-pagos-container
          image: nicolasdcubillos/img-ms-pagos:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
